function [average_calibration] = averageCalibrations(calibrated_systems)

for ii = 1:length(calibrated_systems)    
%     source1 = [source1; ...
%         calibrated_systems{ii}.getSourceLocation(0).x ...
%         calibrated_systems{ii}.getSourceLocation(0).y ...
%         calibrated_systems{ii}.getSourceLocation(0).z]; 
%     source2 = [source2; ...
%         calibrated_systems{ii}.getSourceLocation(1).x ...
%         calibrated_systems{ii}.getSourceLocation(1).y ...
%         calibrated_systems{ii}.getSourceLocation(1).z]; 
%     detector1 = [detector1; ...
%         calibrated_systems{ii}.getDetectorLocation(0).x ...
%         calibrated_systems{ii}.getDetectorLocation(0).y ...
%         calibrated_systems{ii}.getDetectorLocation(0).z]; 
%     detector2 = [detector2; ...
%         calibrated_systems{ii}.getDetectorLocation(1).x ...
%         calibrated_systems{ii}.getDetectorLocation(1).y ...
%         calibrated_systems{ii}.getDetectorLocation(1).z]; 
    
    sdp1Translation = [sdp1Translation; ...
        calibrated_systems{ii}.getSDPTranslation(0).x ...
        calibrated_systems{ii}.getSDPTranslation(0).y ...
        calibrated_systems{ii}.getSDPTranslation(0).z];
    sdp2Translation = [sdp2Translation; ...
        calibrated_systems{ii}.getSDPTranslation(1).x ...
        calibrated_systems{ii}.getSDPTranslation(1).y ...
        calibrated_systems{ii}.getSDPTranslation(1).z];
    sdp1Rotation = [sdp1Rotation; ...
        calibrated_systems{ii}.getSDPRotation(0).x ...
        calibrated_systems{ii}.getSDPRotation(0).y ...
        calibrated_systems{ii}.getSDPRotation(0).z];
    sdp2Rotation = [sdp2Rotation; ...
        calibrated_systems{ii}.getSDPRotation(1).x ...
        calibrated_systems{ii}.getSDPRotation(1).y ...
        calibrated_systems{ii}.getSDPRotation(1).z];
    
    s1_translation = [s1_translation; ...
        calibrated_systems{ii}.getSDP(0).getSource.getTranslation1() ...
        calibrated_systems{ii}.getSDP(0).getSource.getTranslation2() ...
        calibrated_systems{ii}.getSDP(0).getSource.getTranslation3()];
    s2_translation = [s2_translation; ...
        calibrated_systems{ii}.getSDP(1).getSource.getTranslation1() ...
        calibrated_systems{ii}.getSDP(1).getSource.getTranslation2() ...
        calibrated_systems{ii}.getSDP(1).getSource.getTranslation3()];
    s1_rotation = [s1_rotation; ...
        calibrated_systems{ii}.getSDP(0).getSource.getRotation1() ...
        calibrated_systems{ii}.getSDP(0).getSource.getRotation2() ...
        calibrated_systems{ii}.getSDP(0).getSource.getRotation3()];
    s2_rotation = [s2_rotation; ...
        calibrated_systems{ii}.getSDP(1).getSource.getRotation1() ...
        calibrated_systems{ii}.getSDP(1).getSource.getRotation2() ...
        calibrated_systems{ii}.getSDP(1).getSource.getRotation3()];

    d1_translation = [d1_translation; ...
        calibrated_systems{ii}.getSDP(0).getDetector.getTranslation1() ...
        calibrated_systems{ii}.getSDP(0).getDetector.getTranslation2() ...
        calibrated_systems{ii}.getSDP(0).getDetector.getTranslation3()];
    d2_translation = [d2_translation; ...
        calibrated_systems{ii}.getSDP(1).getDetector.getTranslation1() ...
        calibrated_systems{ii}.getSDP(1).getDetector.getTranslation2() ...
        calibrated_systems{ii}.getSDP(1).getDetector.getTranslation3()];
    d1_rotation = [d1_rotation; ...
        calibrated_systems{ii}.getSDP(0).getDetector.getRotation1() ...
        calibrated_systems{ii}.getSDP(0).getDetector.getRotation2() ...
        calibrated_systems{ii}.getSDP(0).getDetector.getRotation3()];
    d2_rotation = [d2_rotation; ...
        calibrated_systems{ii}.getSDP(1).getDetector.getRotation1() ...
        calibrated_systems{ii}.getSDP(1).getDetector.getRotation2() ...
        calibrated_systems{ii}.getSDP(1).getDetector.getRotation3()];
end



new_sdp1_rotation = mean(sdp1Rotation,1);
new_sdp2_rotation = mean(sdp2Rotation,1);
new_sdp1_translation = mean(sdp1Translation,1);
new_sdp2_translation = mean(sdp2Translation,1);

new_s1_rotation = mean(s1_rotation,1);
new_s2_rotation = mean(s2_rotation,1);
new_s1_translation = mean(s1_translation, 1);
new_s2_translation = mean(s2_translation, 1);

new_d1_rotation = mean(d1_rotation,1);
new_d2_rotation = mean(d2_rotation,1);
new_d1_translation = mean(d1_translation, 1);
new_d2_translation = mean(d2_translation, 1);



average_system = ...
    xrg_buildUnperturbedSystem1(...
    2,...
    90,...
    [100000 100000],...
    [100000 100000]);

average_system.getSDP(0).getDetector.setTranslationHorizontal(new_d1_translation(1));                                                                                                                            
average_system.getSDP(0).getDetector.setTranslationVertical(new_d1_translation(2));                                                                                                                              
average_system.getSDP(0).getDetector.setTranslationFromSource(new_d1_translation(3));                                                                                                                            
average_system.getSDP(0).getDetector.setRotationAboutPolar(new_d1_rotation(1));                                                                                                                                  
average_system.getSDP(0).getDetector.setRotationAboutAzimuthal(new_d1_rotation(2));                                                                                                                              
average_system.getSDP(0).getDetector.setRotationAboutNormal(new_d1_rotation(3));                                                                                                                                 
average_system.getSDP(0).getSource.setVerticalTranslation(new_s1_translation(1));                                                                                                                                
average_system.getSDP(0).getSource.setHorizontalTranslation(new_s1_translation(2));                                                                                                                              
average_system.getSDP(0).getSource.setTranslationToDetectorArray(new_s1_translation(3));                                                                                                                         

average_system.getSDP(1).getDetector.setTranslationHorizontal(new_d2_translation(1));                                                                                                                            
average_system.getSDP(1).getDetector.setTranslationVertical(new_d2_translation(2));                                                                                                                              
average_system.getSDP(1).getDetector.setTranslationFromSource(new_d2_translation(3));                                                                                                                            
average_system.getSDP(1).getDetector.setRotationAboutPolar(new_d2_rotation(1));                                                                                                                                  
average_system.getSDP(1).getDetector.setRotationAboutAzimuthal(new_d2_rotation(2));                                                                                                                              
average_system.getSDP(1).getDetector.setRotationAboutNormal(new_d2_rotation(3));                                                                                                                                 
average_system.getSDP(1).getSource.setVerticalTranslation(new_s2_translation(1));                                                                                                                                
average_system.getSDP(1).getSource.setHorizontalTranslation(new_s2_translation(2));                                                                                                                              
average_system.getSDP(1).getSource.setTranslationToDetectorArray(new_s2_translation(3));

average_system.setSDPRotation( ...
    new_sdp1_rotation(1), ...
    new_sdp1_rotation(2), ...
    new_sdp1_rotation(3), ...
    0);
average_system.setSDPTranslation( ...
    new_sdp1_translation(1), ...
    new_sdp1_translation(2), ...
    new_sdp1_translation(3), ...
    0);

average_system.setSDPRotation( ...
    new_sdp2_rotation(1), ...
    new_sdp2_rotation(2), ...
    new_sdp2_rotation(3), ...
    1);
average_system.setSDPTranslation( ...
    new_sdp2_translation(1), ...
    new_sdp2_translation(2), ...
    new_sdp2_translation(3), ...
    1);


return



