%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% xrg_buildPerturbedSystem1
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% function [simulatedActualSystem]...
%     = ...
%     xrg_buildPerturbedSystem1(...
%         detectors,...
%         detectorAngles,...
%         rotationSpread,...
%         rotationDelta,...
%         detectorDistances,...
%         detectorCenterDeltas,...
%         detectorAngleDeltas,...
%         sourceDistances,...
%         sourceCenterDeltas...
%         )
% 
%%
%%

function [simulatedActualSystem]...
    = ...
    xrg_buildPerturbedSystem1(...
        detectors,...
        detectorAngles,...
        rotationSpread,...
        rotationDelta,...
        detectorDistances,...
        detectorCenterDeltas,...
        detectorAngleDeltas,...
        sourceDistances,...
        sourceCenterDeltas...
        )

simulatedActualSystem = ...
    xrg_buildUnperturbedSystem1(...
    detectors,...
    detectorAngles,...
    rotationSpread,...
    detectorDistances,...
    sourceDistances);

%% perturbing rotation on sdps (other than 1st, as 1st sdp determines axis)
for i = 2:detectors
    rot = randCenteredAtZero1(rotationDelta);
    simulatedActualSystem.rotateSDP(rot,i-1);
end

%%
for i = 1:detectors
    
    detectorAngleDeltaPolar       = detectorAngleDeltas(i,1);
    detectorAngleDeltaAzimuthal   = detectorAngleDeltas(i,2);
    detectorAngleDeltaNormal      = detectorAngleDeltas(i,3);
    
    detectorCenterDeltaNormal     = detectorCenterDeltas(i,1);
    detectorCenterDeltaHorizontal = detectorCenterDeltas(i,2);
    detectorCenterDeltaVertical   = detectorCenterDeltas(i,3);
    
    sourceCenterDeltaNormal       = sourceCenterDeltas(i,1);
    sourceCenterDeltaHorizontal   = sourceCenterDeltas(i,2);
    sourceCenterDeltaVertical     = sourceCenterDeltas(i,3);
    
%     %%setting detector angle
    simulatedActualSystem.setDetectorAngles(...
            randCenteredAtZero1(detectorAngleDeltaPolar),...
            randCenteredAtZero1(detectorAngleDeltaAzimuthal),...
            randCenteredAtZero1(detectorAngleDeltaNormal),...
            i-1);

    %%setting detectorTranslation
        simulatedActualSystem.setDetectorTranslation(...
            randCenteredAtZero1(detectorCenterDeltaNormal),... %%change from negative?
            randCenteredAtZero1(detectorCenterDeltaHorizontal),...
            randCenteredAtZero1(detectorCenterDeltaVertical),...
            i-1);

    %setting sourceTranslation
        simulatedActualSystem.setSourceTranslation(...
            randCenteredAtZero1(sourceCenterDeltaNormal),...              %chagne from negative?
            randCenteredAtZero1(sourceCenterDeltaHorizontal),...
            randCenteredAtZero1(sourceCenterDeltaVertical),...
            i-1);
    
end