function [simulatedActualSystem]...
    = ...
        createPerturbedSystem2(...
        detectors,...
        rotationSpread,...
        detectorDistances,...
        sourceDistances,...
        detectorDistanceDeltas,...
        detectorAngleDeltas,...
        sourceDistanceDeltas,...
        sdpTranslationDeltas,...
        sdpRotationDeltas);
        

simulatedActualSystem = ...
    xrg_buildUnperturbedSystem1(...
    detectors,...
    rotationSpread,...
    detectorDistances,...
    sourceDistances);


% simulatedActualSystem
deltas = xrg_getSystemDeltas(simulatedActualSystem)
% 'indelts'
% pause
%setting detectorTranslation
for i = 1:detectors
    focalLengthDelta = detectorDistanceDeltas(i,1);
        simulatedActualSystem.setDetectorTranslation(...
            randCenteredAtZero1(focalLengthDelta),... %%change from negative?
            0,...
            0,...
            i-1);
end

%setting sourceTranslation
for i = 1:detectors
    focalLengthDelta = sourceDistanceDeltas(i,1);
        simulatedActualSystem.setSourceTranslation(...
            randCenteredAtZero1(focalLengthDelta),... %%change from negative?
            0,...
            0,...
            i-1);
end
    
%%translating and rotating each sdp
for i = 1:detectors
    sdpR1 = randCenteredAtZero1(sdpRotationDeltas(i,1));
    sdpR2 = randCenteredAtZero1(sdpRotationDeltas(i,2));
    sdpR3 = randCenteredAtZero1(sdpRotationDeltas(i,3));
    simulatedActualSystem.setSDPRotation(sdpR1, sdpR2, sdpR3, i-1);
    
    sdpT1 = randCenteredAtZero1(sdpTranslationDeltas(i,1));
    sdpT2 = randCenteredAtZero1(sdpTranslationDeltas(i,2));
    sdpT3 = randCenteredAtZero1(sdpTranslationDeltas(i,3));
    simulatedActualSystem.setSDPTranslation(sdpT1, sdpT2, sdpT3, i-1);
end


for i = 1:detectors 
    detectorAngleDeltaPolar       = detectorAngleDeltas(i,1);
    detectorAngleDeltaAzimuthal   = detectorAngleDeltas(i,2);
    detectorAngleDeltaNormal      = detectorAngleDeltas(i,3);
    
    %%setting each detector angle
    simulatedActualSystem.setDetectorAngles(...
            randCenteredAtZero1(detectorAngleDeltaPolar),...
            randCenteredAtZero1(detectorAngleDeltaAzimuthal),...
            randCenteredAtZero1(detectorAngleDeltaNormal),...
            i-1);
end

    %

    
end