clear all;
pack;
pathScript;

reconFiducials = 4;
fiducialDelta = 5000;
detectors = 2;
rotationSpread = 90;
rotationDelta = 0.000001;%%1.000001;
detectorDistances = [450000; 450000];
detectorDistance = detectorDistances(1);
detectorCenterDelta = .0000001;%%5000.000001;
detectorAngleDelta = .000001;%%2.000001;
sourceDistances = [280000; 280000];
sourceDistance = sourceDistances(1);
sourceCenterDelta = .000001;%%5000.000001;
reconOutputDelta = 2.5;

[actualCalibratedSystem]...
    = ...
    createPerturbedSystem1(...
    detectors,...
    rotationSpread,...
    rotationDelta,...
    detectorDistances,...
    detectorCenterDelta,...
    detectorAngleDelta,...
    sourceDistances,...
    sourceCenterDelta);

[expectedCalibratedSystem]...
    = ...
    createUnperturbedSystem1(...
    detectors,...
    rotationSpread,...
    detectorDistances,...
    sourceDistances);

[simulatedValues, actualCalibratedSystem, expectedCalibratedSystem] = ...
    simulateAndReconstruct2(...
    actualCalibratedSystem,...
    expectedCalibratedSystem,...
    fiducialDelta,...
    reconFiducials,...
    reconOutputDelta);

%% harvesting data from the simulation
distance = actualCalibratedSystem.getElectrodeLocation().distance...
    (expectedCalibratedSystem.getElectrodeLocation());

relDistance = actualCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().distance...
    (expectedCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame());

x = actualCalibratedSystem.getElectrodeLocation().x...
    - (expectedCalibratedSystem.getElectrodeLocation().x);

y = actualCalibratedSystem.getElectrodeLocation().y...
    - (expectedCalibratedSystem.getElectrodeLocation().y);

z = actualCalibratedSystem.getElectrodeLocation().z....
    - (expectedCalibratedSystem.getElectrodeLocation().z);

relX = actualCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().x...
    - (expectedCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().x);

relY = actualCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().y...
    - (expectedCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().y);

relZ = actualCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().z...
    - (expectedCalibratedSystem.getElectrodeLocationRelativeToFiducialFrame().z);
