%% collectSimulatedData3 - collects output data 
%% Purturbs the data by some random amount centered at 0 of uniform
%% distribution from -ouputDelta to outputDelta
%% can be used to collect simulated data of rotations

function [simulatedValues, simulatedValuesNoImagingError] = ...
    calib_collectSimulatedData3(...
    simulatedActualSystem,...
    expectedRotations,...
    rotationDelta,...
    outputDelta)

%     simulatedValues =...
%         simulatedActualSystem.getIdealCentersOfProjection();

    str= xrg_getRHS(simulatedActualSystem);
    simulatedValues = str.RHS;
    
    for rot = 1:size(expectedRotations,2)
        rotation = expectedRotations(rot) + randCenteredAtZero1(rotationDelta);
        simulatedActualSystem.rotateFiducials(rotation);
        simulatedValues = ... 
        [simulatedValues; simulatedActualSystem.getIdealCentersOfProjection()];
    end
    %% values without any imaging error
    simulatedValuesNoImagingError = simulatedValues;
    
    %%values perturbed by imaging error
    simulatedValues = simulatedValues + ...
    randCenteredAtZero2(...
    outputDelta,...
    size(simulatedValues,1),...
    size(simulatedValues,2));
end